# Generated by Django 3.0 on 2020-08-23 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('balance', models.FloatField(default=0, verbose_name='Баланс счета')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Это персонал')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='Символ')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('multiplicity', models.SmallIntegerField(verbose_name='Кратность')),
                ('is_base', models.BooleanField(default=False, verbose_name='Эта валюта базовая')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_amount', models.FloatField(verbose_name='Сумма перевода в валюте отправителя')),
                ('recipient_amount', models.FloatField(verbose_name='Сумма перевода в валюте получателя')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время совершаения транзакции')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('recipient_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_transactions', to='money_transporter.Currency', verbose_name='Валюта получателя')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('sender_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_transactions', to='money_transporter.Currency', verbose_name='Валюта отправителя')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время начала действия курса')),
                ('course', models.FloatField(verbose_name='Курс')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='money_transporter.Currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'get_latest_by': 'start_datetime',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='money_transporter.Currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
